name: My First swf:GetWorkflowExecutionHistory

on: push

jobs:
    first_job: 
        runs-on: ubuntu-latest
        steps:
            - name: welcome message 
              run: echo "My First Github Actions"

            - name: List files 
              run: ls 
            
            - name: Read file (if it exists)
              run: |
                if [ -f README.md ]; then
                  cat README.md
                else
                  echo "README.md not found"
                fi