name: My First swf:GetWorkflowExecutionHistory

on: push

jobs:
    first_job: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v5 

            - name: List and Read file  
              run: |
                echo "My First Github Actions"
                ls -ltra 
                cat README.md
  
            - name: List Files 
              run: ls 
            
            - name: Read file (if it exists)
              run: |
               if [ -f README.md ]; then
                 cat README.md
               else
                 echo "README.md not found"
               fi